apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mcr.microsoft.com/mssql/server:2019-latest
        name: sql-server
        env:
        - name: SA_PASSWORD
          value: "YourStrong@Password"
        - name: ACCEPT_EULA
          value: "Y"
        ports:
        - containerPort: 1433
          name: sql-server
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {}